### ISSUE TITLE
Question: Support for CoreML / Vision?

### ISSUE THREAD

**Issue by f0rr0** [heestand-xyz/PixelKit#17]
I was hacking together a demo where I had to do portrait segmentation (Zoom like background removal) without chroma key.
I decided to use Deeplabv3 and found this project: https://github.com/jsharp83/MetalCamera which has all the parts properly setup. With a few minor changes I was able to macOS compatible as well.

This would make a great addition to PixelKit.

My use case is: remove the background from realtime video and merge it with a custom image/video.

Relevant File:
https://github.com/jsharp83/MetalCamera/blob/master/MetalCamera/Classes/CoreML/CoreMLClassifierHandler.swift

**Comment by antonheestand** [comment]
Hi, Deeplabv3 is nice, tho it’s hard to get it going in realtime, I was trying it out here: [DeepLabPIX](https://github.com/antonheestand/PixelKit/blob/ace81606fc33d99354e5b4d027e890fc4704488e/Source/PIX/PIXs/Effects/Single/DeepLabPIX.swift#L22). [SaliencyPIX](https://github.com/antonheestand/PixelKit/blob/ace81606fc33d99354e5b4d027e890fc4704488e/Source/PIX/PIXs/Effects/Single/SaliencyPIX.swift#L17) is faster tho low res. A blur, a threshold, a channel mix and a blend might do the trick.
