### ISSUE TITLE
Low frame rate

### ISSUE THREAD

**Issue by developer-appdam** [heestand-xyz/PixelKit#18]
Hi all,

We are trying to use the CameraPIX together with a MOV that has an alpha channel. 

`                 let camera = CameraPIX()
                    camera.camera = .front
                    let overlay = VideoPIX()
                    overlay.load(fileNamed: "FreeSmokeYoutube", withExtension: "mov") { done in
                    let blend = BlendPIX()
                    blend.blendMode = .addWithAlpha
                    blend.placement = .aspectFill
                    blend.extend = .mirror
                    blend.inputA = camera
                    blend.inputB = overlay
    
                    self.record = RecordPIX()
                    self.record?.input = blend
    
                    try? self.record?.startRec(name: "tempvid")
                }`

The outcome though, it's really low frame rate. This is basically using the default configuration so, what could it be?

Thanks

**Comment by antonheestand** [comment]
Hi, so there is a coulpe things that could be effecting the frame rate; video resolution and fps, device performance. Tho I think it’s actually the recorder. Try chaning these parameters in the [RecordPIX](https://github.com/antonheestand/PixelKit/blob/ace81606fc33d99354e5b4d027e890fc4704488e/Source/PIX/PIXs/Output/RecordPIX.swift#L39). Sorry that the docs are down. Working on trying to get them up again.
