### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by melMass** [heestand-xyz/PixelKit#25]
Hi,

Sorry I was out of the swift/spm loop for two years, as I was still on Mojave, and a lot has changed, querying google gives various options none seems to work.

First of I'm under Catalina and using XCode 12.4 (AFAIK the last version compatible with Catalina). 
My project is a basic SwiftUI macOS app.

In XCode I went to `File >  Swift Packages > Add Package Dependency...` and search for PixelKit.

In the version selection panel I tried a few things:
- Exact == 2.0.4
- Up to Next Major from 2.0.4
- branch "main"

Both returned the following:

![image](https://user-images.githubusercontent.com/7041726/123165651-cae17480-d474-11eb-9a86-daeceaffc974.png)

Very interesting project.

Thanks

**Comment by melMass** [comment]
Ok, I think this lib is macOS 11 only?

![image](https://user-images.githubusercontent.com/7041726/123166256-7f7b9600-d475-11eb-9fe7-15e2fabb22c1.png)

**Comment by melMass** [comment]
Yep, the library is using newer methods and is only compatible with Big Sur

**Comment by heestand-xyz** [comment]
Hi, sorry about that, I've now set the swift tools version to 5.3.
PixelKit 2.0.5 should now be compatible.

**Comment by melMass** [comment]
@heestand-xyz Awesome thanks!
