### ISSUE TITLE
Compatibility with Catalina ?

### ISSUE THREAD

**Issue by melMass** [heestand-xyz/PixelKit#26]
Hi heestand,

Thanks for the fix regarding the swift version, it still won't build, here are the errors, I have linked to the source files:
<details><summary><b>Screenshot of the errors with permalinks to source files</b></summary>

![image](https://user-images.githubusercontent.com/7041726/123313954-49e4b480-d52a-11eb-8df6-d6c9aedebdd9.png)
https://github.com/heestand-xyz/PixelKit/blob/12d5c2c184d23d20db5fecc8438bc6e156a616ac/Source/PIX/PIXs/Effects/Multi/Blends/BlendsPIX.swift#L38

![image](https://user-images.githubusercontent.com/7041726/123314124-7dbfda00-d52a-11eb-9826-5b13b66696d2.png)
https://github.com/heestand-xyz/PixelKit/blob/12d5c2c184d23d20db5fecc8438bc6e156a616ac/Source/PIX/Extensions/ResultBuilders.swift#L11

![image](https://user-images.githubusercontent.com/7041726/123314202-97612180-d52a-11eb-9580-611040a7d9db.png)
https://github.com/heestand-xyz/PixelKit/blob/12d5c2c184d23d20db5fecc8438bc6e156a616ac/Source/PIX/PIXs/Effects/Single/Blur/BlurPIX.swift#L76

![image](https://user-images.githubusercontent.com/7041726/123314557-063e7a80-d52b-11eb-886c-cd44b5ff4e9e.png)
https://github.com/heestand-xyz/PixelKit/blob/12d5c2c184d23d20db5fecc8438bc6e156a616ac/Source/PIX/PX.swift#L146

And this that still tries to compile even with the safeguards (no idea how it's possible, I will thoroughly check my xcode project)

![image](https://user-images.githubusercontent.com/7041726/123314357-c9728380-d52a-11eb-936c-f3c67fbf783f.png)

</details>

Sorry it's very ugly 😅, do you think it will be possible to remediate those issue to be compatible with an older SDK than Big Sur?

Thanks

**Comment by heestand-xyz** [comment]
Thanks for collecting the errors, I can take a look at them in the beginning of next week.

**Comment by heestand-xyz** [comment]
I've now added Swift `5.5` checks in the repo, so now it runs on Xcode `12.2`.
The update is in tag `2.0.7`. I hope it works with your setup.

**Comment by melMass** [comment]
Perfect thanks! 
I will test it tomorrow

**Comment by melMass** [comment]
It works, playing with it I ❤️  the idea.
I'm I right to assume that `StateObject` is interchangeable with `ObservedObject`?

**Comment by heestand-xyz** [comment]
Awesome! Yes, you can pass `PIX` objects via `@ObservedObject` and store them in `@StateObject` in SwiftUI.
