### ISSUE TITLE
Using RecordPIX ?

### ISSUE THREAD

**Issue by osmangorgun** [heestand-xyz/PixelKit#29]
Do you have an example of using video recording?

**Comment by heestand-xyz** [comment]
I recommend using [AsyncGraphics](https://github.com/heestand-xyz/AsyncGraphics), there are articles about using [Live Camera](http://async.graphics/documentation/asyncgraphics/livecamera) and [Video Editing](http://async.graphics/documentation/asyncgraphics/videoediting).
